Repository kubevirt/sig-release, pull requests merged in 2023-07, with the labels that each got.

#8 Moving the v1.0 release date due to various holidays
  releases/v1.0/schedule.md
Labels: dco-signoff: yes, lgtm, size/XS

#10 Rename aliases due to suspected conflict with defaults
  OWNERS
  OWNERS_ALIASES
Labels: dco-signoff: yes

#12 Publish KubeVirt v1.1 Release Schedule
  releases/v1.1/schedule.md
Labels: dco-signoff: yes, size/S, lgtm, approved
